### Value
POST http://localhost:8080/api/scale/keg
Content-Type: text/plain
Authorization: test

24251.55

### Ping
POST http://localhost:8080/api/scale/ping
Content-Type: text/plain
Authorization: test

ping;-74