### Value
POST http://localhost:8080/api/scale/push
Content-Type: text/plain
Authorization: test

push|1234|-74|7000.0

### Ping
POST http://localhost:8080/api/scale/push
Content-Type: text/plain
Authorization: test

ping|1234|-71|